### ISSUE TITLE
Deploying Flagr Architecture

### ISSUE THREAD

**Issue by oleborne** [checkr/flagr#139]
Flagr Architecture references many components:  UI, Flagr, Sync Worker, Evaluator, ...
https://checkr.github.io/flagr/#/flagr_overview?id=flagr-architecture

However, the doc about deployment and configuration is about a single docker image that seem to correspond to the _Flagr Manager_ tier.

It is possible to deploy a scalable installation as the one described in this document?
Where can I find any documentation on how to do so?

Thanks

**Comment by zhouzhuojie** [comment]
The flagr image or flagr binary with static UI asset has everything you need to run, which includes "Flagr Manager" and "Flagr Evaluator". Analytics is not included here, since I can't assume everyone's data pipeline.

For scalable installation, you can deploy as many as flagr nodes as you want behind a load balancer, for example, Kubernetes' DNS, or nginx gateway.

Moreover, every node can serve the traffic for both evaluation and CRUD.
https://checkr.github.io/flagr/api_docs/#tag/evaluation => high QPS endpoints
https://checkr.github.io/flagr/api_docs/#tag/flag       => CRUD endpoints

**Comment by oleborne** [comment]
Brilliant!
Is Redis actually involved? Or are evaluators reading data directly from the DB?

**Comment by zhouzhuojie** [comment]
Good catch! I originally planned to use Redis, but in production, directly read from the DB works for our scale without problems - it's a periodic read with eager loading, and most DB already has the cache for this use case, so I didn't implement the Redis cache yet, which also means one less dependency.

Will update the figure in the doc soon.

**Comment by oleborne** [comment]
Thanks for the information.
I'm really eager to try using Flagr to introduce feature flags in our process.

Is it possible to share the scale you are able to serve with this approach?
No need to provide sensitive information, just round to closest power of 10 or even rougher (DB used, number of instances, flag and evaluation per day).

**Comment by zhouzhuojie** [comment]
Of course, here are some stats in our production

- 5 nodes of flagr for HA
- around 5000 per second for flagr evaluation
- MySQL DB, reloading all flags into memory takes about 50ms

Definitely try it out and benchmark it on your end.

**Comment by oleborne** [comment]
Thank you very much for your help and information.
I'll try to come back and share our experience in a couple month if this experimentation goes forward.
