### ISSUE TITLE
Bulk Evaluation Doesn't Return Variant Information

### ISSUE THREAD

**Issue by MrThreepwood** [checkr/flagr#263]
## Expected Behavior
I would expect that the bulk evaluation endpoint would return the same results as the individual evaluation endpoint.

## Current Behavior
It returns the matched segment ID, but none of the variant information.

## Steps to Reproduce (for bugs)
Always occurs on using bulk evaluate.

## Context
We were hoping to load all flag data into our apps on launch to reduce network calls. At the moment, it looks like we'll need to make a network call per flag.

**Comment by zhouzhuojie** [comment]
Hey @MrThreepwood 

I can't reproduce from debug console and other API calls. You can try it on https://try-flagr.herokuapp.com/#/flags/1
![image](https://user-images.githubusercontent.com/658840/58507346-685b0480-8146-11e9-9b7e-a64bb239e1c8.png)


Maybe, it related to https://github.com/checkr/flagr/releases/tag/1.1.0, instead of returning `null`, the fields are ignored now in the payload of goswagger generated code.

**Comment by MrThreepwood** [comment]
Sorry, I thought that it matched a segment since it was including the segment in the response (and the one for an invalid flagKey did not), but I didn't have a state, so it didn't match the segment. After matching the segment I am indeed getting the segment back. (state = CA).

I do think if the request doesn't actually match a segment it probably shouldn't return one however. In the code it looks like it's just setting the segment to the last one evaluated. It makes more sense to me to only set it if it actually matches.
