### ISSUE TITLE
Docker image for 1.1.4 broken

### ISSUE THREAD

**Issue by jbiel** [checkr/flagr#340]
Flagr fails to start with the following error when attempting to launch the `checkr/flagr:1.1.4` image with Docker.

`Error relocating ./flagr: fcntl64: symbol not found`

This seems to be an issue with missing glibc (understandable in alpine), but from what I can see in master's Dockerfile this shouldn't be an issue. I'm not sure how/why these old versions are built/re-pushed because I don't see branches correlating with versions.

**Comment by zhouzhuojie** [comment]
Yup, 1.1.4 was not safe to rebuild/recreate due to https://github.com/checkr/flagr/pull/281
Please bump to 1.1.5 (if you want minimal changes from 1.1.4), or bump up to 1.1.7 (latest).

ChangeLog: https://github.com/checkr/flagr/blob/master/CHANGELOG.md

**Comment by jbiel** [comment]
We're pulling the old image for 1.1.4 by SHA (`checkr/flagr@sha256:7a13c5ec26ab87070b802f211e5864bcbafc3237077e93fc61536bbeeed080cc`) for now and will plan an upgrade after we've had a chance to verify/test the latest version.

May I ask what the reasoning is for pushing all old image tags? I don't believe I've encountered other projects that do this and it can cause unexpected issues for consumers.

**Comment by zhouzhuojie** [comment]
Sorry for the inconvenience. We are doing maintenance work on all the images hosted on dockerhub. We are moving private images out of docker hub, and we are also examining if the public docker images are affected by [docker hub hack](https://www.zdnet.com/article/docker-hub-hack-exposed-data-of-190000-users/) or not, especially for images built around that time. We don't believe so since we didn't find anything, but still, want to recreate all the tags from source code (checkout from git tag and rebuild) just to be safe. I've checked all the existing tags, and only `1.1.4` crashed on docker run. 

I will push `checkr/flagr@sha256:7a13c5ec26ab87070b802f211e5864bcbafc3237077e93fc61536bbeeed080cc` to `checkr/flagr:1.1.4`, since the newly built image `checkr/flagr:1.1.4` was broken anyway.

**Comment by zhouzhuojie** [comment]
1.1.4 is back. 

https://hub.docker.com/layers/checkr/flagr/1.1.4/images/sha256-7a13c5ec26ab87070b802f211e5864bcbafc3237077e93fc61536bbeeed080cc?context=explore

**Comment by jbiel** [comment]
Thank you!
