### ISSUE TITLE
Higher contrast color scheme

### ISSUE THREAD

**Issue by dcramer** [checkr/flagr#344]
It'd be great if the color scheme could have better contrast. A light blue background with white text is quite difficult to read.

Happy to @ some designers if thats valuable :)

**Comment by zhouzhuojie** [comment]
Yes please! I'm thinking of rewriting / redesign the UI for a while... not a frontend guy, can definitely use some help here.

**Comment by dcramer** [comment]
@ckj maybe you could provide some thoughts?

**Comment by dcramer** [comment]
Also @zhouzhuojie have a color/palette of choice? Can probably whip up a PR with a proposal.

**Comment by ckj** [comment]
@dcramer @zhouzhuojie It looks like the light blue is a brand choice. What if you made the text darker? This one uses the color from the body copy on your website instead of the green var.

<img width="585" alt="flagr_homepage" src="https://user-images.githubusercontent.com/30713/78622149-3a9c1d00-7839-11ea-912a-eebeae83cf57.png">

If you're not partial to the light blue brand-wise, the blue you're using for the active table sort icon is really nice: 

<img width="596" alt="flagr_app_blue" src="https://user-images.githubusercontent.com/30713/78622455-07a65900-783a-11ea-8c55-10a849f32537.png">

**Comment by Cull-Methi** [comment]
On a similar note, I've gotten some requests internally for a 'dark theme' because developers always seem to love their dark themes

**Comment by zhouzhuojie** [comment]
LGTM, the blue can also be the dark blue from https://checkr.com/ :)
And yes, dark theme is awesome!
