### ISSUE TITLE
About generic metrics and tracing capabilities

### ISSUE THREAD

**Issue by jaysonsantos** [checkr/flagr#413]
Hey there, I see that flagr already has a few options for tracing and metrics but they seem to lack a bunch of information, for example, new relic's one. I would like to try and contribute to this and I would like to hear what you think.
My idea is to use something like [opentelemetry](https://opentelemetry.io/) [for go](https://github.com/open-telemetry/opentelemetry-go) to avoid being vendor locked and to have all the features by default.
To avoid a bunch of dependencies, I thought of having a way to build flagr as a library and then subprojects (like flagr-datadog, flagr-newrelic) just configure the global exporter and call flagr's main function, it can also be the same one as now that starts the swagger server.
Ideally, it should at least support what is in there for tracing like data dog and for metrics prometheus can easily be done as it is one of the default exporters that opentelemetry for go implements.
What do you think about it? Is this something that would be useful for the project?

**Comment by zhouzhuojie** [comment]
I think the majority of the users are directly using the docker image and deploy flagr to the cloud - which means the overhead of managing vendors is likely a development problem.

To make it easier for the users, I'd prefer configuration over choosing different flavors of flagr telemetry implementations - imagine this pattern can grow even further like DB flavors, data recording pipelines flavors, and so on. And the downside is that we may need to bundle all the vendors into the binary - which is ok for now since the image size is still manageable. 

And thanks for the idea of refactoring the telemetry part! We'd like to see we have all the flavors of tracing/metrics implemented, and controllable by environment variables. Let me know what do you think?

**Comment by jaysonsantos** [comment]
Hey there, if the final binary size is not a problem I guess it is just a matter of implementing using opentelemetry with vendors subscribers.
I will try to work on this in the near future if no other urgent issues happen on my side.
