### ISSUE TITLE
[QUESTION] EntityType and EntityID and Tracking

### ISSUE THREAD

**Issue by kolbis** [checkr/flagr#419]
Thank you for the great work!

**Entity**
I am evaluating flagr and need some assistance in better understanding the core concepts. Specifically:
- EntityType
- EntityID
What do they actually represent? 
Why are they needed for the evaluation?
In a real life scenario, what should we pass as input?

**Tracking**
In addition, it might be correlated, how do you keep users from getting same variant? 
Is it up to the integration to produce tracking cookie?

**Comment by marceloboeira** [comment]
### Entity

The entity represents the context of what we are going to assign the variant on (the representation of the possible variation of a flag for a given entity). 

Usually, Flagr expects the context coming with the entity, so that one can define constraints based on the context of the entity.

#### EntityID

DOCS:
> entityID is used to deterministically at random to evaluate the flag result. If it's empty, flagr will randomly generate one.

The EntityID is what is going to be used to "hash" and constantly give you one (same) variant. e.g.: if I tell flagr the user_id is - _"a21b09"_ then every time that users, for instance, reloads the page and asks for the flag again, the same variant would be given (unless the flag/distribution configuration changes).

Meaning that you want that to be unique, at least most of the times, per user (e.g.: user_id) 

At the end, it depends on what you are splitting your distribution it based on. It could be that you are releasing a new "product-page" and you want that only 10% of the products have that new design/feature, you could shard based on that rather than the user-id.

#### EntityType

The entity type is more of an annotation of what you used to split the distribution, "user_id" / "admin_user_id" / "product_id" ...

If you set consistently you can use that to get all flags at once to match a specify entityType, e.g.: 1 HTTP request to get all **user_id** based flags.

You can also use an empty entityID/entityType if you just want random could that will cause weird behaviour on stateful services (like web applications with session).

----

> In addition, it might be correlated, how do you keep users from getting same variant?

They will be in buckets depending on the distribution/constraint setup, the entityID is what is building the bridge to identify the stored variant for each "user". 

> Is it up to the integration to produce tracking cookie?

Not sure what you mean, but if by cookie you mean a identifier to the user then yes.

**Comment by kolbis** [comment]
@marceloboeira thank you for the response.  
Understood.

**Comment by marceloboeira** [comment]
I'm glad it helped!
