### ISSUE TITLE
Postgres >= 9 Support

### ISSUE THREAD

**Issue by jnikitin-r7** [checkr/flagr#466]
Hi,

I just wanted to confirm if there was any testing done and its expected that flagr will work with Postgres > 9.6. The docker compose file has version 9 in it, which is 9.6.

9.6 is being deprecated by Postgres in 2 months. And Amazon (AWS) is forcing everyone to upgrade at end of the year. I'm targeting to upgrade to Postgres 12. 

Thank you for any input.

**Comment by marceloboeira** [comment]
@jnikitin-r7 I have added a layer with pgsql 13 to our integration tests at openflagr (community-maintained version of checkr/flagr). Nothing fails, I'm assuming that it should be already compatible with all pgsql from 9 to 13 since we don't do anything too database specific, the drivers are mostly engine-agnostic.

**Comment by jnikitin-r7** [comment]
@marceloboeira thank you very much for the quick response! This gives us a lot of confidence.
